sudo: required
services:
  - docker

before_install:
  - docker build -t dockeryoutube -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeryoutube npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: <encrypted access_key_id>
  secret_access_key: <encrypted secret_access_key>
  bucket: <bucket>
  edge: true # opt in to dpl v2
  