sudo: required
services:
  - docker

before_install:
  - docker build -t dockeryoutube -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeryoutube npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: "$SECRET_ACCESS_KEY"
  REGION: "us-east-1"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-s3-bucket"
  
